#! /bin/sh

sxhkd &

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d 1 2 3 &
done

bspc config border_width         1
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

