#! /bin/sh

bspc config border_width        2
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DVI-I-2  -d 1 2 3 4 5
bspc monitor DVI-I-3  -d 6 7 8 9 10

panel &
