#! /bin/sh

bspc config border_width        2
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DVI-I-2  -d 1 3 5 7 9
bspc monitor DVI-I-3  -d 2 4 6 8 10

panel &
compton & 
